apiVersion: v1
kind: Service
metadata:
  name: django_service
spec:
  selector:
    app: django
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 8000
      targetPort: 8000
